/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import TablaPrestamos.Prestamos;
import TablaPrestamos.PrestamosBD;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shanj
 */
public class PanelAdministracion extends javax.swing.JPanel {

   DefaultTableModel modelo = new DefaultTableModel();
   PrestamosBD  prestamosBD = new PrestamosBD();
   Prestamos prestamos  = new Prestamos();
    public PanelAdministracion() {
        initComponents();
        ListarPrestamo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPrestamos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoIDLibro = new javax.swing.JTextField();
        campoIDEstudiante = new javax.swing.JTextField();
        campoPrestamo = new javax.swing.JTextField();
        campoDevolucion = new javax.swing.JTextField();
        btnGuardarPrestamo = new javax.swing.JButton();
        campoIDPrestamo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnNuevoPrestamo = new javax.swing.JButton();
        recibirPrestamo = new javax.swing.JButton();

        contenedor.setBackground(new java.awt.Color(83, 43, 136));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(217, 217, 217));
        jLabel1.setText("Administración");

        TablaPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Prestamo", "ID LIbro", "ID Estudiante", "Fecha Prestamo", "Fecha Devolucion", "Devuelto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPrestamosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaPrestamos);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Registrar Prestamo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ID Libro");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ID Estudiantes ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Fecha Prestamo");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Fecha Devoución");

        btnGuardarPrestamo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardarPrestamo.setText("Registar Pestamo");
        btnGuardarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPrestamoActionPerformed(evt);
            }
        });

        campoIDPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDPrestamoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Id Prestamo");

        btnNuevoPrestamo.setText("Nuevo");
        btnNuevoPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPrestamoActionPerformed(evt);
            }
        });

        recibirPrestamo.setText("Recibir Prestamo");
        recibirPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recibirPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(campoIDEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(campoPrestamo)
                            .addComponent(campoDevolucion)
                            .addComponent(jLabel6)
                            .addComponent(campoIDLibro)
                            .addComponent(campoIDPrestamo)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNuevoPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(recibirPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoIDPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoIDLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoIDEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnGuardarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNuevoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(recibirPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TablaPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPrestamosMouseClicked
       int row = TablaPrestamos.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "No se Selecciono");
        } else {
           int  idpres = Integer.parseInt((String) TablaPrestamos.getValueAt(row, 0).toString());
            int idlibro = Integer.parseInt((String)  TablaPrestamos.getValueAt(row, 1).toString());
              int idestu = Integer.parseInt((String)  TablaPrestamos.getValueAt(row, 2).toString());
            String fechapres = (String)  TablaPrestamos.getValueAt(row, 3);
            String fechadev =  (String)  TablaPrestamos.getValueAt(row, 4);
           
            campoIDPrestamo.setText(""+idpres);
            campoIDLibro.setText("" + idlibro);
            campoIDEstudiante.setText(""+idestu);
            campoPrestamo.setText(""+fechapres);
            campoDevolucion.setText(""+fechadev);

        }
        
        
        
        
    }//GEN-LAST:event_TablaPrestamosMouseClicked

    private void campoIDPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDPrestamoActionPerformed

    private void btnGuardarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPrestamoActionPerformed
     
//         if( campoIDPrestamo.getText().equals("")) {
        if( campoIDLibro.getText().equals("")|| campoIDEstudiante.getText().equals("")||campoPrestamo.getText().equals("")||campoDevolucion.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Todo los campos son requeridos");
     }else{
         int idlibro = Integer.parseInt(campoIDLibro.getText());
         int idusuario=Integer.parseInt(campoIDEstudiante.getText()) ;
         String fechapres = campoPrestamo.getText();
        String fechadev = campoDevolucion.getText();
     
         prestamos.setIdLibro(idlibro);
         prestamos.setIdUsuario(idusuario);
         prestamos.setFechaPrestamo(fechapres);
         prestamos.setFechaDevolucion(fechadev);
         
         if (prestamosBD.registrarPrestamo(prestamos)) {
                    LimpiarTable();
                    limpiarPrestamo();
                    ListarPrestamo();
                    JOptionPane.showMessageDialog(null, "Prestamo Registrado");
                } else {
                    JOptionPane.showMessageDialog(null, "Error");
                }
        }
         btnGuardarPrestamo.setText("Prestar");
         
//     }else {
//            int pregunta = JOptionPane.showConfirmDialog(null, "¿ Recibir Libro: ", "Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
//            if (pregunta == 0) {
//                if (prestamosBD.actualizarLibro(Integer.parseInt(campoPrestamo.getText()))) {
//                    LimpiarTable();
//                    limpiarPrestamo();
//                    ListarPrestamo();
//                    JOptionPane.showMessageDialog(null, "Prestamo Devuelto");
//                } else {
//                    JOptionPane.showMessageDialog(null, "Error");
//                }
//            }
//               btnGuardarPrestamo.setText("Prestar");
//        }
        
        
    }//GEN-LAST:event_btnGuardarPrestamoActionPerformed

    private void btnNuevoPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPrestamoActionPerformed
          limpiarPrestamo();
         btnGuardarPrestamo.setText("Prestar");
    }//GEN-LAST:event_btnNuevoPrestamoActionPerformed

    private void recibirPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recibirPrestamoActionPerformed
       int pregunta = JOptionPane.showConfirmDialog(null, "¿ Recibir Libro: ", "Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (pregunta == 0) {
                if (prestamosBD.actualizarLibro(Integer.parseInt(campoPrestamo.getText()))) {
                    LimpiarTable();
                    limpiarPrestamo();
                    ListarPrestamo();
                    JOptionPane.showMessageDialog(null, "Prestamo Devuelto");
                } else {
                    JOptionPane.showMessageDialog(null, "Error");
                }
            }
               btnGuardarPrestamo.setText("Prestar");
    }//GEN-LAST:event_recibirPrestamoActionPerformed
 void ListarPrestamo() {
        List <Prestamos> Listar = prestamosBD.Listar();
        modelo = (DefaultTableModel) TablaPrestamos.getModel();
        Object[] ob = new Object[6];
     
        for (int i = 0; i < Listar.size(); i++) {
            ob[0] = Listar.get(i).getIdPrestamo();
            ob[1] = Listar.get(i).getIdLibro();
            ob[2] = Listar.get(i).getIdUsuario();
            ob[3] = Listar.get(i).getFechaPrestamo();
            ob[4] = Listar.get(i).getFechaDevolucion();
            ob[5] = Listar.get(i).getDevuelto();
            modelo.addRow(ob);
        }
        TablaPrestamos.setModel(modelo);
        //color( TablaPrestamos);
    }
  public void LimpiarTable() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }
      private void limpiarPrestamo() {
        campoIDLibro.setText("");
        campoIDEstudiante.setText("");
        campoPrestamo.setText("");
        campoDevolucion.setText("");
        
    }
  
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPrestamos;
    private javax.swing.JButton btnGuardarPrestamo;
    private javax.swing.JButton btnNuevoPrestamo;
    private javax.swing.JTextField campoDevolucion;
    private javax.swing.JTextField campoIDEstudiante;
    private javax.swing.JTextField campoIDLibro;
    private javax.swing.JTextField campoIDPrestamo;
    private javax.swing.JTextField campoPrestamo;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton recibirPrestamo;
    // End of variables declaration//GEN-END:variables
}
