/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import TablaAutores.AutoresBD;
import TablaGeneros.GenerosBD;
import TablaLibros.LibrosBD;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author shanj
 */
public class PanelEstudiante extends javax.swing.JPanel {


 AutoresLibros au=new AutoresLibros( );
    /**
     * Creates new form PanelEstudiante
     */
    public PanelEstudiante() {
        initComponents();
        AutoresLibros au = new AutoresLibros();
        AutoresBD aBD = new AutoresBD();

        ShowPanel(au);
        aBD.listarAutores("autores", au.tablaAutores);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAutores = new javax.swing.JButton();
        btnTitulos = new javax.swing.JButton();
        btnGeneros = new javax.swing.JButton();
        contenedor = new javax.swing.JPanel();

        setBackground(new java.awt.Color(217, 217, 217));

        jPanel1.setBackground(new java.awt.Color(155, 114, 207));

        btnAutores.setBackground(new java.awt.Color(155, 114, 207));
        btnAutores.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnAutores.setForeground(new java.awt.Color(47, 24, 75));
        btnAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/poema.png"))); // NOI18N
        btnAutores.setText("   Autores");
        btnAutores.setBorder(null);
        btnAutores.setBorderPainted(false);
        btnAutores.setContentAreaFilled(false);
        btnAutores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAutores.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnAutoresMouseMoved(evt);
            }
        });
        btnAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoresActionPerformed(evt);
            }
        });

        btnTitulos.setBackground(new java.awt.Color(155, 114, 207));
        btnTitulos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnTitulos.setForeground(new java.awt.Color(47, 24, 75));
        btnTitulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/libros (1).png"))); // NOI18N
        btnTitulos.setText("    Titulos");
        btnTitulos.setBorder(null);
        btnTitulos.setBorderPainted(false);
        btnTitulos.setContentAreaFilled(false);
        btnTitulos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTitulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitulosActionPerformed(evt);
            }
        });

        btnGeneros.setBackground(new java.awt.Color(155, 114, 207));
        btnGeneros.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnGeneros.setForeground(new java.awt.Color(47, 24, 75));
        btnGeneros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/jugar.png"))); // NOI18N
        btnGeneros.setText("   Géneros");
        btnGeneros.setBorder(null);
        btnGeneros.setBorderPainted(false);
        btnGeneros.setContentAreaFilled(false);
        btnGeneros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAutores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTitulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGeneros, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(btnAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnTitulos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1026, 1026, 1026))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTitulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitulosActionPerformed
       TItulosLibros tl = new TItulosLibros();
      LibrosBD lb = new LibrosBD();
      
         ShowPanel(tl);
         lb.listarLibros("libros", tl.tablaTitulos);


    }//GEN-LAST:event_btnTitulosActionPerformed

    private void btnGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerosActionPerformed
     
        GenerosLibros gl = new GenerosLibros();
        GenerosBD gBD =new GenerosBD();
        ShowPanel(gl);
        gBD.listarGeneros("generos", gl.tablaGeneros);
    }//GEN-LAST:event_btnGenerosActionPerformed

    private void btnAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoresActionPerformed
       AutoresLibros au=new AutoresLibros( );
       AutoresBD aBD = new AutoresBD();
     
        
      ShowPanel(au);
      aBD.listarAutores("autores",au.tablaAutores);
  
    }//GEN-LAST:event_btnAutoresActionPerformed

    private void btnAutoresMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAutoresMouseMoved
                    // TODO add your handling code here:
    }//GEN-LAST:event_btnAutoresMouseMoved

   private void ShowPanel(JPanel p){
        p.setSize(1120,761);
        p.setLocation(0,0);       
        contenedor.removeAll();
        contenedor.add(p,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutores;
    private javax.swing.JButton btnGeneros;
    private javax.swing.JButton btnTitulos;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
